var ns = global.nk = {};

require( './nk-base/nk-base' )( ns );
require( './nk-utils/nk-utils' )( ns );
require( './nk-utils/nk-color' )( ns );
require( './nk-style/nk-fill' )( ns );
require( './nk-style/nk-shadow' )( ns );
require( './nk-style/nk-stroke' )( ns );
require( './nk-style/nk-text' )( ns );
require( './nk-style/nk-style' )( ns );
require( './nk-event/nk-local-listener.js' )( ns );
require( './nk-event/nk-local-event.js' )( ns );
require( './nk-time/nk-ticker/nk-ticker.js' )( ns );
require( './nk-time/nk-timer/nk-timer.js' )( ns );
require( './nk-math/nk-vector/nk-vector2d' )( ns );
require( './nk-math/nk-vector/nk-limit-vector2d' )( ns );
require( './nk-math/nk-math' )( ns );
require( './nk-math/nk-collision/nk-collision2d.js' )( ns );
require( './nk-geom/nk-line/nk-line2d' )( ns );
require( './nk-geom/nk-aabb/nk-aabb2d' )( ns );
require( './nk-geom/nk-polygon/nk-polygon2d' )( ns );
require( './nk-geom/nk-circle/nk-circle' )( ns );
require( './nk-input/nk-mouse' )( ns );
require( './nk-input/nk-keyboard' )( ns );
require( './nk-debug/nk-debug' )( ns );
require( './nk-path/nk-line/nk-line2d' )( ns );
require( './nk-path/nk-aabb/nk-aabb2d' )( ns );
require( './nk-path/nk-polygon/nk-polygon2d' )( ns );
require( './nk-path/nk-circle/nk-circle' )( ns );
require( './nk-entity/nk-container2d' )( ns );
require( './nk-entity/nk-stage2d' )( ns );
require( './nk-entity/nk-graphic2d' )( ns );
require( './nk-entity/nk-text' )( ns );
require( './nk-cp/nk-option' )( ns );
require( './nk-cp/nk-command' )( ns );
require( './nk-cp/nk-register' )( ns );

if ( DEVELOPMENT && module.hot ) module.hot.accept();