var namespace = global.nk = global.Nenkraft = {};

require( './nk-base/nk-base' )( namespace );
require( './nk-utils/nk-utils' )( namespace );
require( './nk-utils/nk-color' )( namespace );
require( './nk-style/nk-fill' )( namespace );
require( './nk-style/nk-shadow' )( namespace );
require( './nk-style/nk-stroke' )( namespace );
require( './nk-style/nk-text' )( namespace );
require( './nk-style/nk-style' )( namespace );
require( './nk-event/nk-local-listener.js' )( namespace );
require( './nk-event/nk-local-event.js' )( namespace );
require( './nk-time/nk-ticker/nk-ticker.js' )( namespace );
require( './nk-time/nk-timer/nk-timer.js' )( namespace );
require( './nk-math/nk-vector/nk-vector2d' )( namespace );
require( './nk-math/nk-vector/nk-limit-vector2d' )( namespace );
require( './nk-math/nk-math' )( namespace );
require( './nk-math/nk-transformation-matrix2d' )( namespace );
require( './nk-math/nk-collision/nk-collision2d.js' )( namespace );
require( './nk-geom/nk-line/nk-line2d' )( namespace );
require( './nk-geom/nk-aabb/nk-aabb2d' )( namespace );
require( './nk-geom/nk-polygon/nk-polygon2d' )( namespace );
require( './nk-geom/nk-circle/nk-circle' )( namespace );
require( './nk-input/nk-mouse' )( namespace );
require( './nk-input/nk-keyboard' )( namespace );
require( './nk-debug/nk-debug' )( namespace );
require( './nk-path/nk-line/nk-line2d' )( namespace );
require( './nk-path/nk-aabb/nk-aabb2d' )( namespace );
require( './nk-path/nk-polygon/nk-polygon2d' )( namespace );
require( './nk-path/nk-circle/nk-circle' )( namespace );
require( './nk-entity/nk-container2d' )( namespace );
require( './nk-entity/nk-stage2d' )( namespace );
require( './nk-entity/nk-graphic2d' )( namespace );
require( './nk-entity/nk-text' )( namespace );
require( './nk-entity/nk-sprite' )( namespace );
require( './nk-cp/nk-option' )( namespace );
require( './nk-cp/nk-command' )( namespace );
require( './nk-cp/nk-register' )( namespace );
require( './nk-load/nk-texture-loader' )( namespace );

if ( DEVELOPMENT && module.hot ) module.hot.accept();